// <auto-generated />
namespace CustomStrategyGameBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableDetailsRefinedV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableDetailsRefinedV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812122103237_TableDetailsRefinedV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
